version: '3.8'

services:
  partypics:
    container_name: partypics
    environment:
      - PYTHONUNBUFFERED=1

      - FLASK_APP=main.py
      - FLASK_DEBUG=${FLASK_DEBUG:-True}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}    
      - SECRET_KEY=${SECRET_KEY:-mysecretkey}
    ports:
      - "8209:${FLASK_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build
